sonar.projectKey=tekton-pipeline-queue
sonar.projectName=tekton-pipeline-queue
sonar.projectVersion=1.0
sonar.go.coverage.reportPaths=cover.out
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/config/**,**/deploy-templates/**,**/main.go,**/api/**,**/hack/**,**/mocks/**
