---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edp-{{ .Values.name }}-{{ .Release.Namespace }}-role
  labels:
    {{- include "tekton-pipeline-queue.labels" . | nindent 4 }}
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - pipelinerunqueues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - pipelinerunqueues/status
  verbs:
  - get
  - patch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - get
  - list
  - patch
  - watch
